apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: slo-istio
  namespace: monitoring
  labels:
    release: prometheus
    team: platform-engineering
    env: prod
spec:
  service: "istio"
  labels:
    cluster: "prod-us-east-2"
    component: "kubernetes"
    team: "platform-engineering"
  slos:
    - name: "istio-agent-convergence-time"
      objective: 99.995
      description: "Ensure that istio agents converge quickly"
      labels:
        category: latency
      sli:
        events:
          errorQuery: (sum(rate(istio_agent_pilot_proxy_convergence_time_count[{{.window}}])) - sum(rate(istio_agent_pilot_proxy_convergence_time_bucket{le="0.5"}[{{.window}}])))
          totalQuery: sum(rate(istio_agent_pilot_proxy_convergence_time_count[{{.window}}]))
      alerting:
        name: Istio proxy convergence
        labels:
          category: "latency"
        annotations:
          summary: "High latency detected"
        pageAlert:
          labels:
            severity: critical
        ticketAlert:
          labels:
            severity: warning
    - name: "istiod-uptime"
      objective: 99.99
      description: "Ensure that istiod is running"
      labels:
        category: availability
      sli:
        raw:
          errorRatioQuery: (1 - max by(app) (irate(istiod_uptime_seconds[{{.window}}])) or on () vector(1))
      alerting:
        name: Istio availability
        labels:
          category: "availability"
        annotations:
          summary: "Low availability detected"
        pageAlert:
          labels:
            severity: critical
        ticketAlert:
          labels:
            severity: warning
